# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MobiePosterScrapper.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 451, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tabHome = QtWidgets.QWidget()
        self.tabHome.setObjectName("tabHome")
        self.labelHomeTitle = QtWidgets.QLabel(self.tabHome)
        self.labelHomeTitle.setGeometry(QtCore.QRect(10, 10, 421, 141))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.labelHomeTitle.setFont(font)
        self.labelHomeTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHomeTitle.setWordWrap(True)
        self.labelHomeTitle.setObjectName("labelHomeTitle")
        self.tabWidget.addTab(self.tabHome, "")
        self.tabSingle = QtWidgets.QWidget()
        self.tabSingle.setObjectName("tabSingle")
        self.lineEditSingleIn = QtWidgets.QLineEdit(self.tabSingle)
        self.lineEditSingleIn.setGeometry(QtCore.QRect(20, 40, 311, 28))
        self.lineEditSingleIn.setObjectName("lineEditSingleIn")
        self.labelSingleTitle = QtWidgets.QLabel(self.tabSingle)
        self.labelSingleTitle.setGeometry(QtCore.QRect(20, 10, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelSingleTitle.setFont(font)
        self.labelSingleTitle.setObjectName("labelSingleTitle")
        self.buttonSingleSearch = QtWidgets.QPushButton(self.tabSingle)
        self.buttonSingleSearch.setGeometry(QtCore.QRect(340, 40, 93, 28))
        self.buttonSingleSearch.setObjectName("buttonSingleSearch")
        self.tabWidget.addTab(self.tabSingle, "")
        self.tabMultiple = QtWidgets.QWidget()
        self.tabMultiple.setObjectName("tabMultiple")
        self.buttonChooseFile = QtWidgets.QPushButton(self.tabMultiple)
        self.buttonChooseFile.setGeometry(QtCore.QRect(20, 50, 93, 28))
        self.buttonChooseFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonChooseFile.setObjectName("buttonChooseFile")
        self.labelMultipleInput = QtWidgets.QLabel(self.tabMultiple)
        self.labelMultipleInput.setGeometry(QtCore.QRect(20, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMultipleInput.setFont(font)
        self.labelMultipleInput.setObjectName("labelMultipleInput")
        self.comboFileTypeIn = QtWidgets.QComboBox(self.tabMultiple)
        self.comboFileTypeIn.setGeometry(QtCore.QRect(130, 50, 121, 28))
        self.comboFileTypeIn.setObjectName("comboFileTypeIn")
        self.comboFileTypeIn.addItem("")
        self.comboFileTypeIn.addItem("")
        self.comboFileTypeIn.addItem("")
        self.comboFileTypeIn.addItem("")
        self.comboFileTypeIn.addItem("")
        self.comboFileTypeIn.addItem("")
        self.comboFileTypeIn.addItem("")
        self.comboFileTypeOut = QtWidgets.QComboBox(self.tabMultiple)
        self.comboFileTypeOut.setGeometry(QtCore.QRect(20, 120, 93, 28))
        self.comboFileTypeOut.setObjectName("comboFileTypeOut")
        self.comboFileTypeOut.addItem("")
        self.comboFileTypeOut.addItem("")
        self.comboFileTypeOut.addItem("")
        self.comboFileTypeOut.addItem("")
        self.comboFileTypeOut.addItem("")
        self.comboFileTypeOut.addItem("")
        self.comboFileTypeOut.addItem("")
        self.comboFormatOut = QtWidgets.QComboBox(self.tabMultiple)
        self.comboFormatOut.setGeometry(QtCore.QRect(130, 120, 121, 31))
        self.comboFormatOut.setObjectName("comboFormatOut")
        self.comboFormatOut.addItem("")
        self.comboFormatOut.addItem("")
        self.comboFormatOut.addItem("")
        self.pushMultipleStart = QtWidgets.QPushButton(self.tabMultiple)
        self.pushMultipleStart.setGeometry(QtCore.QRect(270, 50, 101, 101))
        self.pushMultipleStart.setObjectName("pushMultipleStart")
        self.labelMultipleOutput = QtWidgets.QLabel(self.tabMultiple)
        self.labelMultipleOutput.setGeometry(QtCore.QRect(20, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMultipleOutput.setFont(font)
        self.labelMultipleOutput.setObjectName("labelMultipleOutput")
        self.labelError = QtWidgets.QLabel(self.tabMultiple)
        self.labelError.setGeometry(QtCore.QRect(20, 160, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelError.setFont(font)
        self.labelError.setText("")
        self.labelError.setObjectName("labelError")
        self.tabWidget.addTab(self.tabMultiple, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Movie Poster Srapper"))
        self.labelHomeTitle.setText(_translate("MainWindow", "Movie Poster Scrapper"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHome), _translate("MainWindow", "Home"))
        self.labelSingleTitle.setText(_translate("MainWindow", "Enter Movie Title"))
        self.buttonSingleSearch.setText(_translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSingle), _translate("MainWindow", "Single Movie"))
        self.buttonChooseFile.setText(_translate("MainWindow", "Choose File"))
        self.labelMultipleInput.setText(_translate("MainWindow", "Input File"))
        self.comboFileTypeIn.setItemText(0, _translate("MainWindow", "File Type"))
        self.comboFileTypeIn.setItemText(1, _translate("MainWindow", ".txt"))
        self.comboFileTypeIn.setItemText(2, _translate("MainWindow", ".doc or .docx"))
        self.comboFileTypeIn.setItemText(3, _translate("MainWindow", ".xls or .xlsx"))
        self.comboFileTypeIn.setItemText(4, _translate("MainWindow", ".csv"))
        self.comboFileTypeIn.setItemText(5, _translate("MainWindow", ".tsv"))
        self.comboFileTypeIn.setItemText(6, _translate("MainWindow", ".pdf"))
        self.comboFileTypeOut.setItemText(0, _translate("MainWindow", "File Type"))
        self.comboFileTypeOut.setItemText(1, _translate("MainWindow", ".txt"))
        self.comboFileTypeOut.setItemText(2, _translate("MainWindow", ".doc or .docx"))
        self.comboFileTypeOut.setItemText(3, _translate("MainWindow", ".xls or .xlsx"))
        self.comboFileTypeOut.setItemText(4, _translate("MainWindow", ".csv"))
        self.comboFileTypeOut.setItemText(5, _translate("MainWindow", ".tsv"))
        self.comboFileTypeOut.setItemText(6, _translate("MainWindow", ".pdf"))
        self.comboFormatOut.setItemText(0, _translate("MainWindow", "Format"))
        self.comboFormatOut.setItemText(1, _translate("MainWindow", "Link"))
        self.comboFormatOut.setItemText(2, _translate("MainWindow", "Movie Title & Link"))
        self.pushMultipleStart.setText(_translate("MainWindow", "Start"))
        self.labelMultipleOutput.setText(_translate("MainWindow", "Output File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMultiple), _translate("MainWindow", "Multiple Movies"))

